version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: ${PG_CONTAINER_NAME}
    restart: unless-stopped
    env_file: ./.env.dev
    volumes:
      - postgres_data_geogem:/data/geogem-postgres
    networks:
      - network
    ports:
      - "5432:5432"

networks:
  network:
    driver: bridge

volumes:
  postgres_data_geogem:
    external: true  
